# Generated by Django 5.1.3 on 2024-11-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_topicnode"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicnode",
            name="board_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="topicnode",
            name="board_name",
            field=models.CharField(default="default", max_length=255),
        ),
    ]
