# Generated by Django 5.1.3 on 2024-11-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_topicnode_board_id_topicnode_board_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicnode",
            name="node_level",
            field=models.IntegerField(default=1),
        ),
    ]
