# Generated by Django 5.1.3 on 2024-12-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_topicnode_node_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=255, unique=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField()),
                ("date", models.CharField(max_length=255)),
                ("tags", models.JSONField()),
                ("parent_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
