# Generated by Django 5.1.3 on 2024-12-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_linknode"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicnode",
            name="child_ids",
            field=models.JSONField(default=list),
        ),
    ]
