# Generated by Django 5.1.3 on 2025-01-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_linknode_position_x_linknode_position_y_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="linknode",
            old_name="position_x",
            new_name="x",
        ),
        migrations.RenameField(
            model_name="linknode",
            old_name="position_y",
            new_name="y",
        ),
        migrations.RenameField(
            model_name="topicnode",
            old_name="position_x",
            new_name="x",
        ),
        migrations.RenameField(
            model_name="topicnode",
            old_name="position_y",
            new_name="y",
        ),
    ]
